"""Add document file metadata

Revision ID: 8c5dde0e3ecb
Revises: 63331d386c15
Create Date: 2026-08-13 17:30:46.535190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5dde0e3ecb'
down_revision = '63331d386c15'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "file_type",
                sa.String(length=20),
                nullable=False,
                server_default="text",
            )
        )

        batch_op.add_column(
            sa.Column(
                "file_path",
                sa.String(length=500),
                nullable=True,
            )
        )

        batch_op.add_column(
            sa.Column(
                "original_filename",
                sa.String(length=255),
                nullable=True,
            )
        )

        batch_op.alter_column(
            "file_type",
            server_default=None,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('original_filename')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
